### ISSUE TITLE
Demo applicatie die op logt met referentie naar het verwerkingsregister

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/gemma-verwerkingen#17]

**Comment by joeribekker** [comment]
Zie: https://verwerkingsregister.vng.cloud

**Comment by adgerrits** [comment]
Is het de bedoeling dat je in de demoapp als admin ingelogd bent? Want dat is nu zo als je er heen gaat.

**Comment by joeribekker** [comment]
Er zijn 2 apps:

1. De demo applicatie die de processtap(pen) logt. Hiervoor hoef je niet in te loggen en mag je alle bouwaanvragen inzien en/of goed- of afkeuren. Er worden vanzelf nieuwe aangemaakt.
Zie: https://verwerkingsregister.vng.cloud/demo/

2. Het verwerkingsregister. Hiervoor moet je inderdaad inloggen. Ik heb even een demo gebruiker aangemaakt: preview/commonground  Gelieve niets te wijzigen. Zie: https://verwerkingsregister.vng.cloud/admin/datamodel/rule/
